#include "instruct.h"
#include "frame.h"
#include "java.h"

#define OP_WIDE         -1
#define OP_TABLESWITCH  -2
#define OP_LOOKUPSWITCH -3

static int op_nop(Frame *frame);
static int op_pop(Frame *frame);
static int op_pop2(Frame *frame);
static int op_bipush(Frame *frame);
static int op_sipush(Frame *frame);
static int op_istore_1(Frame *frame);
static int op_istore_2(Frame *frame);
static int op_istore_3(Frame *frame);
static int op_iload_1(Frame *frame);
static int op_iload_2(Frame *frame);
static int op_iload_3(Frame *frame);
static int op_iadd(Frame *frame);
static int op_ireturn(Frame *frame);

static int noperands[] = {
	[NOP]             = 0,
	[ACONST_NULL]     = 0,
	[ICONST_M1]       = 0,
	[ICONST_0]        = 0,
	[ICONST_1]        = 0,
	[ICONST_2]        = 0,
	[ICONST_3]        = 0,
	[ICONST_4]        = 0,
	[ICONST_5]        = 0,
	[LCONST_0]        = 0,
	[LCONST_1]        = 0,
	[FCONST_0]        = 0,
	[FCONST_1]        = 0,
	[FCONST_2]        = 0,
	[DCONST_0]        = 0,
	[DCONST_1]        = 0,
	[BIPUSH]          = 1,
	[SIPUSH]          = 2,
	[LDC]             = 1,
	[LDC_W]           = 2,
	[LDC2_W]          = 2,
	[ILOAD]           = 1,
	[LLOAD]           = 1,
	[FLOAD]           = 1,
	[DLOAD]           = 1,
	[ALOAD]           = 1,
	[ILOAD_0]         = 0,
	[ILOAD_1]         = 0,
	[ILOAD_2]         = 0,
	[ILOAD_3]         = 0,
	[LLOAD_0]         = 0,
	[LLOAD_1]         = 0,
	[LLOAD_2]         = 0,
	[LLOAD_3]         = 0,
	[FLOAD_0]         = 0,
	[FLOAD_1]         = 0,
	[FLOAD_2]         = 0,
	[FLOAD_3]         = 0,
	[DLOAD_0]         = 0,
	[DLOAD_1]         = 0,
	[DLOAD_2]         = 0,
	[DLOAD_3]         = 0,
	[ALOAD_0]         = 0,
	[ALOAD_1]         = 0,
	[ALOAD_2]         = 0,
	[ALOAD_3]         = 0,
	[IALOAD]          = 0,
	[LALOAD]          = 0,
	[FALOAD]          = 0,
	[DALOAD]          = 0,
	[AALOAD]          = 0,
	[BALOAD]          = 0,
	[CALOAD]          = 0,
	[SALOAD]          = 0,
	[ISTORE]          = 1,
	[LSTORE]          = 1,
	[FSTORE]          = 1,
	[DSTORE]          = 1,
	[ASTORE]          = 1,
	[ISTORE_0]        = 0,
	[ISTORE_1]        = 0,
	[ISTORE_2]        = 0,
	[ISTORE_3]        = 0,
	[LSTORE_0]        = 0,
	[LSTORE_1]        = 0,
	[LSTORE_2]        = 0,
	[LSTORE_3]        = 0,
	[FSTORE_0]        = 0,
	[FSTORE_1]        = 0,
	[FSTORE_2]        = 0,
	[FSTORE_3]        = 0,
	[DSTORE_0]        = 0,
	[DSTORE_1]        = 0,
	[DSTORE_2]        = 0,
	[DSTORE_3]        = 0,
	[ASTORE_0]        = 0,
	[ASTORE_1]        = 0,
	[ASTORE_2]        = 0,
	[ASTORE_3]        = 0,
	[IASTORE]         = 0,
	[LASTORE]         = 0,
	[FASTORE]         = 0,
	[DASTORE]         = 0,
	[AASTORE]         = 0,
	[BASTORE]         = 0,
	[CASTORE]         = 0,
	[SASTORE]         = 0,
	[POP]             = 0,
	[POP2]            = 0,
	[DUP]             = 0,
	[DUP_X1]          = 0,
	[DUP_X2]          = 0,
	[DUP2]            = 0,
	[DUP2_X1]         = 0,
	[DUP2_X2]         = 0,
	[SWAP]            = 0,
	[IADD]            = 0,
	[LADD]            = 0,
	[FADD]            = 0,
	[DADD]            = 0,
	[ISUB]            = 0,
	[LSUB]            = 0,
	[FSUB]            = 0,
	[DSUB]            = 0,
	[IMUL]            = 0,
	[LMUL]            = 0,
	[FMUL]            = 0,
	[DMUL]            = 0,
	[IDIV]            = 0,
	[LDIV]            = 0,
	[FDIV]            = 0,
	[DDIV]            = 0,
	[IREM]            = 0,
	[LREM]            = 0,
	[FREM]            = 0,
	[DREM]            = 0,
	[INEG]            = 0,
	[LNEG]            = 0,
	[FNEG]            = 0,
	[DNEG]            = 0,
	[ISHL]            = 0,
	[LSHL]            = 0,
	[ISHR]            = 0,
	[LSHR]            = 0,
	[IUSHR]           = 0,
	[LUSHR]           = 0,
	[IAND]            = 0,
	[LAND]            = 0,
	[IOR]             = 0,
	[LOR]             = 0,
	[IXOR]            = 0,
	[LXOR]            = 0,
	[IINC]            = 2,
	[I2L]             = 0,
	[I2F]             = 0,
	[I2D]             = 0,
	[L2I]             = 0,
	[L2F]             = 0,
	[L2D]             = 0,
	[F2I]             = 0,
	[F2L]             = 0,
	[F2D]             = 0,
	[D2I]             = 0,
	[D2L]             = 0,
	[D2F]             = 0,
	[I2B]             = 0,
	[I2C]             = 0,
	[I2S]             = 0,
	[LCMP]            = 0,
	[FCMPL]           = 0,
	[FCMPG]           = 0,
	[DCMPL]           = 0,
	[DCMPG]           = 0,
	[IFEQ]            = 2,
	[IFNE]            = 2,
	[IFLT]            = 2,
	[IFGE]            = 2,
	[IFGT]            = 2,
	[IFLE]            = 2,
	[IF_ICMPEQ]       = 2,
	[IF_ICMPNE]       = 2,
	[IF_ICMPLT]       = 2,
	[IF_ICMPGE]       = 2,
	[IF_ICMPGT]       = 2,
	[IF_ICMPLE]       = 2,
	[IF_ACMPEQ]       = 2,
	[IF_ACMPNE]       = 2,
	[GOTO]            = 2,
	[JSR]             = 2,
	[RET]             = 1,
	[TABLESWITCH]     = OP_TABLESWITCH,
	[LOOKUPSWITCH]    = OP_LOOKUPSWITCH,
	[IRETURN]         = 0,
	[LRETURN]         = 0,
	[FRETURN]         = 0,
	[DRETURN]         = 0,
	[ARETURN]         = 0,
	[RETURN]          = 0,
	[GETSTATIC]       = 2,
	[PUTSTATIC]       = 2,
	[GETFIELD]        = 2,
	[PUTFIELD]        = 2,
	[INVOKEVIRTUAL]   = 2,
	[INVOKESPECIAL]   = 2,
	[INVOKESTATIC]    = 2,
	[INVOKEINTERFACE] = 4,
	[INVOKEDYNAMIC]   = 4,
	[NEW]             = 2,
	[NEWARRAY]        = 1,
	[ANEWARRAY]       = 2,
	[ARRAYLENGTH]     = 0,
	[ATHROW]          = 0,
	[CHECKCAST]       = 2,
	[INSTANCEOF]      = 2,
	[MONITORENTER]    = 0,
	[MONITOREXIT]     = 0,
	[WIDE]            = OP_WIDE,
	[MULTIANEWARRAY]  = 3,
	[IFNULL]          = 2,
	[IFNONNULL]       = 2,
	[GOTO_W]          = 4,
	[JSR_W]           = 4,
};


static char *instrnames[CODE_LAST] = {
	[NOP]             = "nop",
	[ACONST_NULL]     = "aconst_null",
	[ICONST_M1]       = "iconst_m1",
	[ICONST_0]        = "iconst_0",
	[ICONST_1]        = "iconst_1",
	[ICONST_2]        = "iconst_2",
	[ICONST_3]        = "iconst_3",
	[ICONST_4]        = "iconst_4",
	[ICONST_5]        = "iconst_5",
	[LCONST_0]        = "lconst_0",
	[LCONST_1]        = "lconst_1",
	[FCONST_0]        = "fconst_0",
	[FCONST_1]        = "fconst_1",
	[FCONST_2]        = "fconst_2",
	[DCONST_0]        = "dconst_0",
	[DCONST_1]        = "dconst_1",
	[BIPUSH]          = "bipush",
	[SIPUSH]          = "sipush",
	[LDC]             = "ldc",
	[LDC_W]           = "ldc_w",
	[LDC2_W]          = "ldc2_w",
	[ILOAD]           = "iload",
	[LLOAD]           = "lload",
	[FLOAD]           = "fload",
	[DLOAD]           = "dload",
	[ALOAD]           = "aload",
	[ILOAD_0]         = "iload_0",
	[ILOAD_1]         = "iload_1",
	[ILOAD_2]         = "iload_2",
	[ILOAD_3]         = "iload_3",
	[LLOAD_0]         = "lload_0",
	[LLOAD_1]         = "lload_1",
	[LLOAD_2]         = "lload_2",
	[LLOAD_3]         = "lload_3",
	[FLOAD_0]         = "fload_0",
	[FLOAD_1]         = "fload_1",
	[FLOAD_2]         = "fload_2",
	[FLOAD_3]         = "fload_3",
	[DLOAD_0]         = "dload_0",
	[DLOAD_1]         = "dload_1",
	[DLOAD_2]         = "dload_2",
	[DLOAD_3]         = "dload_3",
	[ALOAD_0]         = "aload_0",
	[ALOAD_1]         = "aload_1",
	[ALOAD_2]         = "aload_2",
	[ALOAD_3]         = "aload_3",
	[IALOAD]          = "iaload",
	[LALOAD]          = "laload",
	[FALOAD]          = "faload",
	[DALOAD]          = "daload",
	[AALOAD]          = "aaload",
	[BALOAD]          = "baload",
	[CALOAD]          = "caload",
	[SALOAD]          = "saload",
	[ISTORE]          = "istore",
	[LSTORE]          = "lstore",
	[FSTORE]          = "fstore",
	[DSTORE]          = "dstore",
	[ASTORE]          = "astore",
	[ISTORE_0]        = "istore_0",
	[ISTORE_1]        = "istore_1",
	[ISTORE_2]        = "istore_2",
	[ISTORE_3]        = "istore_3",
	[LSTORE_0]        = "lstore_0",
	[LSTORE_1]        = "lstore_1",
	[LSTORE_2]        = "lstore_2",
	[LSTORE_3]        = "lstore_3",
	[FSTORE_0]        = "fstore_0",
	[FSTORE_1]        = "fstore_1",
	[FSTORE_2]        = "fstore_2",
	[FSTORE_3]        = "fstore_3",
	[DSTORE_0]        = "dstore_0",
	[DSTORE_1]        = "dstore_1",
	[DSTORE_2]        = "dstore_2",
	[DSTORE_3]        = "dstore_3",
	[ASTORE_0]        = "astore_0",
	[ASTORE_1]        = "astore_1",
	[ASTORE_2]        = "astore_2",
	[ASTORE_3]        = "astore_3",
	[IASTORE]         = "iastore",
	[LASTORE]         = "lastore",
	[FASTORE]         = "fastore",
	[DASTORE]         = "dastore",
	[AASTORE]         = "aastore",
	[BASTORE]         = "bastore",
	[CASTORE]         = "castore",
	[SASTORE]         = "sastore",
	[POP]             = "pop",
	[POP2]            = "pop2",
	[DUP]             = "dup",
	[DUP_X1]          = "dup_x1",
	[DUP_X2]          = "dup_x2",
	[DUP2]            = "dup2",
	[DUP2_X1]         = "dup2_x1",
	[DUP2_X2]         = "dup2_x2",
	[SWAP]            = "swap",
	[IADD]            = "iadd",
	[LADD]            = "ladd",
	[FADD]            = "fadd",
	[DADD]            = "dadd",
	[ISUB]            = "isub",
	[LSUB]            = "lsub",
	[FSUB]            = "fsub",
	[DSUB]            = "dsub",
	[IMUL]            = "imul",
	[LMUL]            = "lmul",
	[FMUL]            = "fmul",
	[DMUL]            = "dmul",
	[IDIV]            = "idiv",
	[LDIV]            = "ldiv",
	[FDIV]            = "fdiv",
	[DDIV]            = "ddiv",
	[IREM]            = "irem",
	[LREM]            = "lrem",
	[FREM]            = "frem",
	[DREM]            = "drem",
	[INEG]            = "ineg",
	[LNEG]            = "lneg",
	[FNEG]            = "fneg",
	[DNEG]            = "dneg",
	[ISHL]            = "ishl",
	[LSHL]            = "lshl",
	[ISHR]            = "ishr",
	[LSHR]            = "lshr",
	[IUSHR]           = "iushr",
	[LUSHR]           = "lushr",
	[IAND]            = "iand",
	[LAND]            = "land",
	[IOR]             = "ior",
	[LOR]             = "lor",
	[IXOR]            = "ixor",
	[LXOR]            = "lxor",
	[IINC]            = "iinc",
	[I2L]             = "i2l",
	[I2F]             = "i2f",
	[I2D]             = "i2d",
	[L2I]             = "l2i",
	[L2F]             = "l2f",
	[L2D]             = "l2d",
	[F2I]             = "f2i",
	[F2L]             = "f2l",
	[F2D]             = "f2d",
	[D2I]             = "d2i",
	[D2L]             = "d2l",
	[D2F]             = "d2f",
	[I2B]             = "i2b",
	[I2C]             = "i2c",
	[I2S]             = "i2s",
	[LCMP]            = "lcmp",
	[FCMPL]           = "fcmpl",
	[FCMPG]           = "fcmpg",
	[DCMPL]           = "dcmpl",
	[DCMPG]           = "dcmpg",
	[IFEQ]            = "ifeq",
	[IFNE]            = "ifne",
	[IFLT]            = "iflt",
	[IFGE]            = "ifge",
	[IFGT]            = "ifgt",
	[IFLE]            = "ifle",
	[IF_ICMPEQ]       = "if_icmpeq",
	[IF_ICMPNE]       = "if_icmpne",
	[IF_ICMPLT]       = "if_icmplt",
	[IF_ICMPGE]       = "if_icmpge",
	[IF_ICMPGT]       = "if_icmpgt",
	[IF_ICMPLE]       = "if_icmple",
	[IF_ACMPEQ]       = "if_acmpeq",
	[IF_ACMPNE]       = "if_acmpne",
	[GOTO]            = "goto",
	[JSR]             = "jsr",
	[RET]             = "ret",
	[TABLESWITCH]     = "tableswitch",
	[LOOKUPSWITCH]    = "lookupswitch",
	[IRETURN]         = "ireturn",
	[LRETURN]         = "lreturn",
	[FRETURN]         = "freturn",
	[DRETURN]         = "dreturn",
	[ARETURN]         = "areturn",
	[RETURN]          = "return",
	[GETSTATIC]       = "getstatic",
	[PUTSTATIC]       = "putstatic",
	[GETFIELD]        = "getfield",
	[PUTFIELD]        = "putfield",
	[INVOKEVIRTUAL]   = "invokevirtual",
	[INVOKESPECIAL]   = "invokespecial",
	[INVOKESTATIC]    = "invokestatic",
	[INVOKEINTERFACE] = "invokeinterface",
	[INVOKEDYNAMIC]   = "invokedynamic",
	[NEW]             = "new",
	[NEWARRAY]        = "newarray",
	[ANEWARRAY]       = "anewarray",
	[ARRAYLENGTH]     = "arraylength",
	[ATHROW]          = "athrow",
	[CHECKCAST]       = "checkcast",
	[INSTANCEOF]      = "instanceof",
	[MONITORENTER]    = "monitorenter",
	[MONITOREXIT]     = "monitorexit",
	[WIDE]            = "wide",
	[MULTIANEWARRAY]  = "multianewarray",
	[IFNULL]          = "ifnull",
	[IFNONNULL]       = "ifnonnull",
	[GOTO_W]          = "goto_w",
	[JSR_W]           = "jsr_w",
};

static INSTRUCT instrtab[] = {
	[NOP]             = op_nop,
	[ACONST_NULL]     = op_nop,
	[ICONST_M1]       = op_nop,
	[ICONST_0]        = op_nop,
	[ICONST_1]        = op_nop,
	[ICONST_2]        = op_nop,
	[ICONST_3]        = op_nop,
	[ICONST_4]        = op_nop,
	[ICONST_5]        = op_nop,
	[LCONST_0]        = op_nop,
	[LCONST_1]        = op_nop,
	[FCONST_0]        = op_nop,
	[FCONST_1]        = op_nop,
	[FCONST_2]        = op_nop,
	[DCONST_0]        = op_nop,
	[DCONST_1]        = op_nop,
	[BIPUSH]          = op_bipush,
	[SIPUSH]          = op_sipush,
	[LDC]             = op_nop,
	[LDC_W]           = op_nop,
	[LDC2_W]          = op_nop,
	[ILOAD]           = op_nop,
	[LLOAD]           = op_nop,
	[FLOAD]           = op_nop,
	[DLOAD]           = op_nop,
	[ALOAD]           = op_nop,
	[ILOAD_0]         = op_nop,
	[ILOAD_1]         = op_iload_1,
	[ILOAD_2]         = op_iload_2,
	[ILOAD_3]         = op_iload_3,
	[LLOAD_0]         = op_nop,
	[LLOAD_1]         = op_nop,
	[LLOAD_2]         = op_nop,
	[LLOAD_3]         = op_nop,
	[FLOAD_0]         = op_nop,
	[FLOAD_1]         = op_nop,
	[FLOAD_2]         = op_nop,
	[FLOAD_3]         = op_nop,
	[DLOAD_0]         = op_nop,
	[DLOAD_1]         = op_nop,
	[DLOAD_2]         = op_nop,
	[DLOAD_3]         = op_nop,
	[ALOAD_0]         = op_nop,
	[ALOAD_1]         = op_nop,
	[ALOAD_2]         = op_nop,
	[ALOAD_3]         = op_nop,
	[IALOAD]          = op_nop,
	[LALOAD]          = op_nop,
	[FALOAD]          = op_nop,
	[DALOAD]          = op_nop,
	[AALOAD]          = op_nop,
	[BALOAD]          = op_nop,
	[CALOAD]          = op_nop,
	[SALOAD]          = op_nop,
	[ISTORE]          = op_nop,
	[LSTORE]          = op_nop,
	[FSTORE]          = op_nop,
	[DSTORE]          = op_nop,
	[ASTORE]          = op_nop,
	[ISTORE_0]        = op_nop,
	[ISTORE_1]        = op_istore_1,
	[ISTORE_2]        = op_istore_2,
	[ISTORE_3]        = op_istore_3,
	[LSTORE_0]        = op_nop,
	[LSTORE_1]        = op_nop,
	[LSTORE_2]        = op_nop,
	[LSTORE_3]        = op_nop,
	[FSTORE_0]        = op_nop,
	[FSTORE_1]        = op_nop,
	[FSTORE_2]        = op_nop,
	[FSTORE_3]        = op_nop,
	[DSTORE_0]        = op_nop,
	[DSTORE_1]        = op_nop,
	[DSTORE_2]        = op_nop,
	[DSTORE_3]        = op_nop,
	[ASTORE_0]        = op_nop,
	[ASTORE_1]        = op_nop,
	[ASTORE_2]        = op_nop,
	[ASTORE_3]        = op_nop,
	[IASTORE]         = op_nop,
	[LASTORE]         = op_nop,
	[FASTORE]         = op_nop,
	[DASTORE]         = op_nop,
	[AASTORE]         = op_nop,
	[BASTORE]         = op_nop,
	[CASTORE]         = op_nop,
	[SASTORE]         = op_nop,
	[POP]             = op_pop,
	[POP2]            = op_pop2,
	[DUP]             = op_nop,
	[DUP_X1]          = op_nop,
	[DUP_X2]          = op_nop,
	[DUP2]            = op_nop,
	[DUP2_X1]         = op_nop,
	[DUP2_X2]         = op_nop,
	[SWAP]            = op_nop,
	[IADD]            = op_iadd,
	[LADD]            = op_nop,
	[FADD]            = op_nop,
	[DADD]            = op_nop,
	[ISUB]            = op_nop,
	[LSUB]            = op_nop,
	[FSUB]            = op_nop,
	[DSUB]            = op_nop,
	[IMUL]            = op_nop,
	[LMUL]            = op_nop,
	[FMUL]            = op_nop,
	[DMUL]            = op_nop,
	[IDIV]            = op_nop,
	[LDIV]            = op_nop,
	[FDIV]            = op_nop,
	[DDIV]            = op_nop,
	[IREM]            = op_nop,
	[LREM]            = op_nop,
	[FREM]            = op_nop,
	[DREM]            = op_nop,
	[INEG]            = op_nop,
	[LNEG]            = op_nop,
	[FNEG]            = op_nop,
	[DNEG]            = op_nop,
	[ISHL]            = op_nop,
	[LSHL]            = op_nop,
	[ISHR]            = op_nop,
	[LSHR]            = op_nop,
	[IUSHR]           = op_nop,
	[LUSHR]           = op_nop,
	[IAND]            = op_nop,
	[LAND]            = op_nop,
	[IOR]             = op_nop,
	[LOR]             = op_nop,
	[IXOR]            = op_nop,
	[LXOR]            = op_nop,
	[IINC]            = op_nop,
	[I2L]             = op_nop,
	[I2F]             = op_nop,
	[I2D]             = op_nop,
	[L2I]             = op_nop,
	[L2F]             = op_nop,
	[L2D]             = op_nop,
	[F2I]             = op_nop,
	[F2L]             = op_nop,
	[F2D]             = op_nop,
	[D2I]             = op_nop,
	[D2L]             = op_nop,
	[D2F]             = op_nop,
	[I2B]             = op_nop,
	[I2C]             = op_nop,
	[I2S]             = op_nop,
	[LCMP]            = op_nop,
	[FCMPL]           = op_nop,
	[FCMPG]           = op_nop,
	[DCMPL]           = op_nop,
	[DCMPG]           = op_nop,
	[IFEQ]            = op_nop,
	[IFNE]            = op_nop,
	[IFLT]            = op_nop,
	[IFGE]            = op_nop,
	[IFGT]            = op_nop,
	[IFLE]            = op_nop,
	[IF_ICMPEQ]       = op_nop,
	[IF_ICMPNE]       = op_nop,
	[IF_ICMPLT]       = op_nop,
	[IF_ICMPGE]       = op_nop,
	[IF_ICMPGT]       = op_nop,
	[IF_ICMPLE]       = op_nop,
	[IF_ACMPEQ]       = op_nop,
	[IF_ACMPNE]       = op_nop,
	[GOTO]            = op_nop,
	[JSR]             = op_nop,
	[RET]             = op_nop,
	[TABLESWITCH]     = op_nop,
	[LOOKUPSWITCH]    = op_nop,
	[IRETURN]         = op_ireturn,
	[LRETURN]         = op_nop,
	[FRETURN]         = op_nop,
	[DRETURN]         = op_nop,
	[ARETURN]         = op_nop,
	[RETURN]          = op_nop,
	[GETSTATIC]       = op_nop,
	[PUTSTATIC]       = op_nop,
	[GETFIELD]        = op_nop,
	[PUTFIELD]        = op_nop,
	[INVOKEVIRTUAL]   = op_nop,
	[INVOKESPECIAL]   = op_nop,
	[INVOKESTATIC]    = op_nop,
	[INVOKEINTERFACE] = op_nop,
	[INVOKEDYNAMIC]   = op_nop,
	[NEW]             = op_nop,
	[NEWARRAY]        = op_nop,
	[ANEWARRAY]       = op_nop,
	[ARRAYLENGTH]     = op_nop,
	[ATHROW]          = op_nop,
	[CHECKCAST]       = op_nop,
	[INSTANCEOF]      = op_nop,
	[MONITORENTER]    = op_nop,
	[MONITOREXIT]     = op_nop,
	[WIDE]            = op_nop,
	[MULTIANEWARRAY]  = op_nop,
	[IFNULL]          = op_nop,
	[IFNONNULL]       = op_nop,
	[GOTO_W]          = op_nop,
	[JSR_W]           = op_nop,
};

/* Get number of operands of a given instruction */
int getNoperands(U1 instruction) {
	return noperands[instruction];
}

/* Get op name. */
char *getOpName(U1 instruct) {
    return instrnames[instruct];
}

/* Get instruct. */
INSTRUCT getInstruct(U1 instruction) {
    return instrtab[instruction];
}

/* nop: do nothing. */
static int op_nop(Frame *frame) {
    UNUSED(frame);
    return NO_RETURN;
}

/* pop: pop the top op statck value. */
static int op_pop(Frame *frame) {
    frameStatckPop(frame);
    return NO_RETURN;
}

/* pop: pop the top one or tow op statck values. */
static int op_pop2(Frame *frame) {
    frameStatckPop(frame);
    frameStatckPop(frame);
    return NO_RETURN;
}

/* bipush: push one byte to op stack. */
static int op_bipush(Frame *frame) {
    Value v;
    v.i = frame->code->code[frame->pc++];
    frameStatckPush(frame, v);
    return NO_RETURN;
}

/* sipush: push a short value into op statck. */
static int op_sipush(Frame *frame) {
    Value v;
    U2 u;

    u = frame->code->code[frame->pc++] << 8;
    u |= frame->code->code[frame->pc++];
    v.i = (I2)u;
    frameStatckPush(frame, v);
    return NO_RETURN;
}

/* istore_1: store int into local variable. */
static int op_istore_1(Frame *frame) {
    Value v;
    v = frameStatckPop(frame);
    frameLocalStore(frame, 1, v);
    return NO_RETURN;
}

/* istore_2: store int into local variable. */
static int op_istore_2(Frame *frame) {
    Value v;
    v = frameStatckPop(frame);
    frameLocalStore(frame, 2, v);
    return NO_RETURN;
}


/* istore_3: store int into local variable. */
static int op_istore_3(Frame *frame) {
    Value v;
    v = frameStatckPop(frame);
    frameLocalStore(frame, 3, v);
    return NO_RETURN;
}

/* load_1: load int from local variable. */
static int op_iload_1(Frame *frame) {
    Value v;
    v = frameLocalLoad(frame, 1);
    frameStatckPush(frame, v);
    return NO_RETURN;
}

/* load_2: load int from local variable. */
static int op_iload_2(Frame *frame) {
    Value v;
    v = frameLocalLoad(frame, 2);
    frameStatckPush(frame, v);
    return NO_RETURN;
}

/* load_3: load int from local variable. */
static int op_iload_3(Frame *frame) {
    Value v;
    v = frameLocalLoad(frame, 3);
    frameStatckPush(frame, v);
    return NO_RETURN;
}

/* iadd: add int. */
static int op_iadd(Frame *frame) {
    Value v1, v2;
    v1 = frameStatckPop(frame);
    v2 = frameStatckPop(frame);
    v1.i += v2.i;
    frameStatckPush(frame, v1);
    return NO_RETURN;
}

/* ireturn: return something from method. */
static int op_ireturn(Frame *frame) {
    UNUSED(frame);
    return RETURN_OPERAND;
}
